stages:
  - build
  - test
  - deploy
 

default:
  image: alpine
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

variables:
  IMAGE_PATH: reg.cicd.tlow.ir/ista/votting-app
  VERSION: v1.0.6

vote-build-job:
  stage: build
  image: docker:dind
  script:
    - cd vote
    - docker build -t ${IMAGE_PATH}/vote:$CI_COMMIT_SHORT_SHA .
    - docker push ${IMAGE_PATH}/vote:$CI_COMMIT_SHORT_SHA
  